// <auto-generated />
namespace WebShared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelaxScrapedDomainsModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelaxScrapedDomainsModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201505011033579_RelaxScrapedDomainsModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
