// <auto-generated />
namespace WebShared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ServerRefreshObject_SoaValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServerRefreshObject_SoaValues));
        
        string IMigrationMetadata.Id
        {
            get { return "201504231637047_ServerRefreshObject_SoaValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
